/*
 * DUT configuration for the RISC-V ACT4 framework (riscv-arch-test).
 *
 * YanOS is RV32IM plus Zicsr (mstatus/mtvec/mscratch/mepc/mcause/mtval) and
 * Zifencei, M-mode only. The define conventions follow the framework: an
 * extension is declared with NAME_SUPPORTED, and the UDB_* names carry the
 * parameters the framework computes its test plan from.
 *
 * SPDX-License-Identifier: BSD-3-Clause-Clear
 */

#ifndef YANOS_RV32IM_RVTEST_CONFIG_H
#define YANOS_RV32IM_RVTEST_CONFIG_H

/* Implemented extensions */
#define I_SUPPORTED
#define I2P1_SUPPORTED
#define M_SUPPORTED
#define M2P0_SUPPORTED
#define SM_SUPPORTED
#define SM1P11P0_SUPPORTED
#define ZICSR_SUPPORTED
#define ZICSR2P0_SUPPORTED
#define ZIFENCEI_SUPPORTED
#define ZIFENCEI2P0_SUPPORTED
#define ZMMUL_SUPPORTED
#define ZMMUL1P0P0_SUPPORTED

/* Configuration parameters */
#define UDB_MISALIGNED_LDST_EXCEPTION_PRIORITY_LOW
#define UDB_MTVAL_WIDTH 32
#define UDB_MTVAL_WIDTH_32
#define UDB_MTVEC_ACCESS_RW
#define UDB_MTVEC_BASE_ALIGNMENT_DIRECT 4
#define UDB_MTVEC_BASE_ALIGNMENT_DIRECT_4
#define UDB_MTVEC_ILLEGAL_WRITE_BEHAVIOR_RETAIN
#define UDB_MTVEC_MODES_0
#define UDB_MXLEN 32
#define UDB_MXLEN_32
#define UDB_M_MODE_ENDIANNESS_LITTLE
#define UDB_NUM_PMP_ENTRIES 0
#define UDB_NUM_PMP_ENTRIES_0
#define UDB_PHYS_ADDR_WIDTH 32
#define UDB_PHYS_ADDR_WIDTH_32
#define UDB_PMA_GRANULARITY 2
#define UDB_PMA_GRANULARITY_2
#define UDB_PRECISE_SYNCHRONOUS_EXCEPTIONS
#define UDB_REPORT_ENCODING_IN_MTVAL_ON_ILLEGAL_INSTRUCTION
#define UDB_REPORT_VA_IN_MTVAL_ON_BREAKPOINT
#define UDB_REPORT_VA_IN_MTVAL_ON_INSTRUCTION_ACCESS_FAULT
#define UDB_REPORT_VA_IN_MTVAL_ON_INSTRUCTION_MISALIGNED
#define UDB_REPORT_VA_IN_MTVAL_ON_LOAD_ACCESS_FAULT
#define UDB_REPORT_VA_IN_MTVAL_ON_LOAD_MISALIGNED
#define UDB_REPORT_VA_IN_MTVAL_ON_STORE_AMO_ACCESS_FAULT
#define UDB_REPORT_VA_IN_MTVAL_ON_STORE_AMO_MISALIGNED
#define UDB_TRAP_ON_EBREAK
#define UDB_TRAP_ON_ECALL_FROM_M
#define UDB_TRAP_ON_RESERVED_INSTRUCTION
#define UDB_TRAP_ON_UNIMPLEMENTED_CSR
#define UDB_TRAP_ON_UNIMPLEMENTED_INSTRUCTION
#define UDB_VENDOR_ID_BANK 0
#define UDB_VENDOR_ID_BANK_0
#define UDB_VENDOR_ID_OFFSET 0
#define UDB_VENDOR_ID_OFFSET_0

#endif /* YANOS_RV32IM_RVTEST_CONFIG_H */
